"""create_tables

Revision ID: fbd589ae3caa
Revises: 
Create Date: 2026-07-23 19:59:08.471941
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fbd589ae3caa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(32), nullable=False),
    sa.Column('status', sa.String(32), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(32), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('audit_log_actor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_index('idx_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_log_actor_id', 'audit_log', ['actor_id'], unique=False)
    op.create_index('idx_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_log_tenant_id', 'audit_log', ['tenant_id'], unique=False)
    op.create_table('projects',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('default_browser', sa.String(), nullable=False),
    sa.Column('default_timeout', sa.Integer(), nullable=False),
    sa.Column('authentication_type', sa.String(), nullable=True),
    sa.Column('repository_url', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('projects_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index('idx_projects_created_by', 'projects', ['created_by'], unique=False)
    op.create_index('idx_projects_environment', 'projects', ['environment'], unique=False)
    op.create_index('idx_projects_name', 'projects', ['name'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_projects_tenant_id', 'projects', ['tenant_id'], unique=False)
    op.create_table('runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('trigger_type', sa.String(32), nullable=False),
    sa.Column('trigger_source', sa.String(), nullable=True),
    sa.Column('environment_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(32), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('progress_percent', sa.SmallInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('workspace_path', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('node_execution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('runs_project_id_fkey')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('runs_requested_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('runs_pkey')),
    sa.UniqueConstraint('run_id', name=op.f('runs_run_id_key'))
    )
    op.create_index('idx_runs_created_at', 'runs', ['created_at'], unique=False)
    op.create_index('idx_runs_requested_by', 'runs', ['requested_by'], unique=False)
    op.create_index('idx_runs_run_id', 'runs', ['run_id'], unique=False)
    op.create_index('idx_runs_status', 'runs', ['status'], unique=False)
    op.create_index('idx_runs_tenant_project', 'runs', ['tenant_id', 'project_id', 'created_at'], unique=False)
    op.create_index('idx_runs_trigger_source', 'runs', ['trigger_source'], unique=False)
    op.create_table('crawl_packages',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(32), nullable=False),
    sa.Column('pages_visited', sa.Integer(), nullable=False),
    sa.Column('pages_skipped', sa.Integer(), nullable=False),
    sa.Column('total_links', sa.Integer(), nullable=False),
    sa.Column('crawl_depth_reached', sa.SmallInteger(), nullable=False),
    sa.Column('bytes_downloaded', sa.BigInteger(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=False),
    sa.Column('auth_method', sa.String(), nullable=True),
    sa.Column('har_path', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('crawl_packages_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('crawl_packages_pkey'))
    )
    op.create_index('idx_crawl_packages_run_id', 'crawl_packages', ['run_id'], unique=True)
    op.create_table('inventories',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('form_count', sa.Integer(), nullable=False),
    sa.Column('link_count', sa.Integer(), nullable=False),
    sa.Column('button_count', sa.Integer(), nullable=False),
    sa.Column('input_count', sa.Integer(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('api_call_count', sa.Integer(), nullable=False),
    sa.Column('user_flow_count', sa.Integer(), nullable=False),
    sa.Column('screenshot_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_pages_removed', sa.Integer(), nullable=False),
    sa.Column('duplicate_links_removed', sa.Integer(), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=False),
    sa.Column('auth_method', sa.String(), nullable=True),
    sa.Column('pages_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('elements_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('navigation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('inventories_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventories_pkey'))
    )
    op.create_index('idx_inventories_run_id', 'inventories', ['run_id'], unique=True)
    op.create_table('test_plans',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(32), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('prompt_hash', sa.String(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('prompt_latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('module_count', sa.SmallInteger(), nullable=False),
    sa.Column('scenario_count', sa.SmallInteger(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('coverage_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('application_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('json_path', sa.String(), nullable=False),
    sa.Column('md_path', sa.String(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('test_plans_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_plans_pkey')),
    sa.UniqueConstraint('run_id', 'version', name='uq_test_plans_run_version')
    )
    op.create_index('idx_test_plans_is_latest', 'test_plans', ['is_latest'], unique=False)
    op.create_index('idx_test_plans_run_id', 'test_plans', ['run_id'], unique=False)
    op.create_table('human_reviews',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('test_plan_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(32), nullable=False),
    sa.Column('decision', sa.String(32), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_name', sa.String(), nullable=False),
    sa.Column('reviewer_email', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_scenarios', sa.SmallInteger(), nullable=False),
    sa.Column('approved_scenarios', sa.SmallInteger(), nullable=False),
    sa.Column('rejected_scenarios', sa.SmallInteger(), nullable=False),
    sa.Column('modified_scenarios', sa.SmallInteger(), nullable=False),
    sa.Column('disabled_scenarios', sa.SmallInteger(), nullable=False),
    sa.Column('decision_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('general_comments', sa.Text(), nullable=True),
    sa.Column('approval_summary', sa.Text(), nullable=True),
    sa.Column('auto_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_plan_path', sa.String(), nullable=False),
    sa.Column('approved_md_path', sa.String(), nullable=True),
    sa.Column('review_metadata_path', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('human_reviews_reviewer_id_fkey')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('human_reviews_run_id_fkey')),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], name=op.f('human_reviews_test_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('human_reviews_pkey')),
    sa.UniqueConstraint('run_id', 'version', name='uq_human_reviews_run_version')
    )
    op.create_index('idx_human_reviews_reviewer_id', 'human_reviews', ['reviewer_id'], unique=False)
    op.create_index('idx_human_reviews_run_id', 'human_reviews', ['run_id'], unique=False)
    op.create_index('idx_human_reviews_status', 'human_reviews', ['status'], unique=False)
    op.create_table('ir_documents',
    sa.Column('test_plan_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('ir_schema_version', sa.String(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('refinement_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('total_pages', sa.SmallInteger(), nullable=False),
    sa.Column('total_elements', sa.SmallInteger(), nullable=False),
    sa.Column('total_flows', sa.SmallInteger(), nullable=False),
    sa.Column('total_modules', sa.SmallInteger(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('prompt_latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ir_path', sa.String(), nullable=False),
    sa.Column('dep_graph_path', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('ir_documents_run_id_fkey')),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], name=op.f('ir_documents_test_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ir_documents_pkey')),
    sa.UniqueConstraint('test_plan_id', 'version', name='uq_ir_documents_plan_version')
    )
    op.create_index('idx_ir_documents_is_latest', 'ir_documents', ['is_latest'], unique=False)
    op.create_index('idx_ir_documents_run_id', 'ir_documents', ['run_id'], unique=False)
    op.create_table('test_scenarios',
    sa.Column('test_plan_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('target_page', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('preconditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('test_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('required_test_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plans.id'], name=op.f('test_scenarios_test_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_scenarios_pkey')),
    sa.UniqueConstraint('test_plan_id', 'scenario_id', name='uq_test_scenarios_plan_scenario')
    )
    op.create_index('idx_test_scenarios_category', 'test_scenarios', ['category'], unique=False)
    op.create_index('idx_test_scenarios_module', 'test_scenarios', ['module_name'], unique=False)
    op.create_index('idx_test_scenarios_plan_id', 'test_scenarios', ['test_plan_id'], unique=False)
    op.create_index('idx_test_scenarios_priority', 'test_scenarios', ['priority'], unique=False)
    op.create_index('idx_test_scenarios_risk_level', 'test_scenarios', ['risk_level'], unique=False)
    op.create_table('generated_projects',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('ir_document_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(32), nullable=False),
    sa.Column('project_path', sa.String(), nullable=False),
    sa.Column('ir_path', sa.String(), nullable=True),
    sa.Column('metadata_path', sa.String(), nullable=False),
    sa.Column('files_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('files_generated', sa.SmallInteger(), nullable=False),
    sa.Column('page_objects_count', sa.SmallInteger(), nullable=False),
    sa.Column('test_files_count', sa.SmallInteger(), nullable=False),
    sa.Column('scenarios_implemented', sa.SmallInteger(), nullable=False),
    sa.Column('modules_covered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_lines_of_code', sa.Integer(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('validation_errors', sa.SmallInteger(), nullable=False),
    sa.Column('validation_warnings', sa.SmallInteger(), nullable=False),
    sa.Column('generation_duration_seconds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['ir_document_id'], ['ir_documents.id'], name=op.f('generated_projects_ir_document_id_fkey')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('generated_projects_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('generated_projects_pkey'))
    )
    op.create_index('idx_generated_projects_run_id', 'generated_projects', ['run_id'], unique=True)
    op.create_table('executions',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('trigger_type', sa.String(32), nullable=False),
    sa.Column('environment_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(32), nullable=False),
    sa.Column('browser', sa.String(), nullable=False),
    sa.Column('headless', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('tests_passed', sa.Integer(), nullable=False),
    sa.Column('tests_failed', sa.Integer(), nullable=False),
    sa.Column('tests_skipped', sa.Integer(), nullable=False),
    sa.Column('tests_flaky', sa.Integer(), nullable=False),
    sa.Column('pass_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_duration_seconds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('health_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('health_status', sa.String(), nullable=True),
    sa.Column('metrics_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('playwright_exit_code', sa.SmallInteger(), nullable=True),
    sa.Column('artifacts_path', sa.String(), nullable=False),
    sa.Column('reports_path', sa.String(), nullable=False),
    sa.Column('execution_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['generated_projects.id'], name=op.f('executions_project_id_fkey')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('executions_run_id_fkey')),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('executions_triggered_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('executions_pkey'))
    )
    op.create_index('idx_executions_created_at', 'executions', ['created_at'], unique=False)
    op.create_index('idx_executions_pass_rate', 'executions', ['pass_rate'], unique=False)
    op.create_index('idx_executions_run_id', 'executions', ['run_id'], unique=True)
    op.create_index('idx_executions_status', 'executions', ['status'], unique=False)
    op.create_index('idx_executions_trigger_type', 'executions', ['trigger_type'], unique=False)
    op.create_table('test_results',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(32), nullable=False),
    sa.Column('duration_ms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('was_retried', sa.Boolean(), nullable=False),
    sa.Column('original_status', sa.String(32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stack', sa.Text(), nullable=True),
    sa.Column('failure_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('test_results_execution_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('test_results_pkey')),
    sa.UniqueConstraint('execution_id', 'title', 'file', name='uq_test_results_exec_title_file')
    )
    op.create_index('idx_test_results_execution_id', 'test_results', ['execution_id'], unique=False)
    op.create_index('idx_test_results_execution_status', 'test_results', ['execution_id', 'status'], unique=False)
    op.create_index('idx_test_results_title', 'test_results', ['title'], unique=False)
    op.create_table('artifacts',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('test_result_id', sa.UUID(), nullable=True),
    sa.Column('artifact_type', sa.String(32), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('storage_backend', sa.String(32), nullable=False),
    sa.Column('storage_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('artifacts_execution_id_fkey')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], name=op.f('artifacts_run_id_fkey')),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], name=op.f('artifacts_test_result_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('artifacts_pkey'))
    )
    op.create_index('idx_artifacts_execution_id', 'artifacts', ['execution_id'], unique=False)
    op.create_index('idx_artifacts_run_id', 'artifacts', ['run_id'], unique=False)
    op.create_index('idx_artifacts_storage_backend', 'artifacts', ['storage_backend'], unique=False)
    op.create_index('idx_artifacts_type', 'artifacts', ['artifact_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_artifacts_type', table_name='artifacts')
    op.drop_index('idx_artifacts_storage_backend', table_name='artifacts')
    op.drop_index('idx_artifacts_run_id', table_name='artifacts')
    op.drop_index('idx_artifacts_execution_id', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('idx_test_results_title', table_name='test_results')
    op.drop_index('idx_test_results_execution_status', table_name='test_results')
    op.drop_index('idx_test_results_execution_id', table_name='test_results')
    op.drop_table('test_results')
    op.drop_index('idx_executions_trigger_type', table_name='executions')
    op.drop_index('idx_executions_status', table_name='executions')
    op.drop_index('idx_executions_run_id', table_name='executions')
    op.drop_index('idx_executions_pass_rate', table_name='executions')
    op.drop_index('idx_executions_created_at', table_name='executions')
    op.drop_table('executions')
    op.drop_index('idx_generated_projects_run_id', table_name='generated_projects')
    op.drop_table('generated_projects')
    op.drop_index('idx_test_scenarios_risk_level', table_name='test_scenarios')
    op.drop_index('idx_test_scenarios_priority', table_name='test_scenarios')
    op.drop_index('idx_test_scenarios_plan_id', table_name='test_scenarios')
    op.drop_index('idx_test_scenarios_module', table_name='test_scenarios')
    op.drop_index('idx_test_scenarios_category', table_name='test_scenarios')
    op.drop_table('test_scenarios')
    op.drop_index('idx_ir_documents_run_id', table_name='ir_documents')
    op.drop_index('idx_ir_documents_is_latest', table_name='ir_documents')
    op.drop_table('ir_documents')
    op.drop_index('idx_human_reviews_status', table_name='human_reviews')
    op.drop_index('idx_human_reviews_run_id', table_name='human_reviews')
    op.drop_index('idx_human_reviews_reviewer_id', table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index('idx_test_plans_run_id', table_name='test_plans')
    op.drop_index('idx_test_plans_is_latest', table_name='test_plans')
    op.drop_table('test_plans')
    op.drop_index('idx_inventories_run_id', table_name='inventories')
    op.drop_table('inventories')
    op.drop_index('idx_crawl_packages_run_id', table_name='crawl_packages')
    op.drop_table('crawl_packages')
    op.drop_index('idx_runs_trigger_source', table_name='runs')
    op.drop_index('idx_runs_tenant_project', table_name='runs')
    op.drop_index('idx_runs_status', table_name='runs')
    op.drop_index('idx_runs_run_id', table_name='runs')
    op.drop_index('idx_runs_requested_by', table_name='runs')
    op.drop_index('idx_runs_created_at', table_name='runs')
    op.drop_table('runs')
    op.drop_index('idx_projects_tenant_id', table_name='projects')
    op.drop_index('idx_projects_name', table_name='projects', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_projects_environment', table_name='projects')
    op.drop_index('idx_projects_created_by', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_audit_log_tenant_id', table_name='audit_log')
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    op.drop_index('idx_audit_log_created_at', table_name='audit_log')
    op.drop_index('idx_audit_log_actor_id', table_name='audit_log')
    op.drop_index('idx_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_users_tenant_id', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users', postgresql_where='deleted_at IS NULL')
    op.drop_table('users')
    # ### end Alembic commands ###
