"""Request/Response schemas."""

from app.schemas.project import (
    CreateProjectRequest,
    DashboardStats,
    ProjectResponse,
    ProjectStats,
    RunListResponse,
    TestRunResponse,
)
from app.schemas.crawler import (
    ApiCallRecord,
    AssetRecord,
    AssetsCollection,
    AuthRecord,
    ButtonRecord,
    CheckboxRecord,
    CookieRecord,
    CrawlEvent,
    CrawlPackage,
    CrawlRequest,
    CrawlStatistics,
    CrawlSummary,
    DialogRecord,
    DownloadRecord,
    DropdownRecord,
    FormRecord,
    InputRecord,
    NavigationEdge,
    NavigationGraph,
    PageRecord,
    RadioRecord,
    RedirectRecord,
    ResponseTimeStats,
    ScreenshotRecord,
    SessionInfo,
    TableRecord,
    UploadRecord,
    UserFlowRecord,
)
from app.schemas.inventory import (
    Inventory,
    InventoryMetadata,
    InventoryNavigation,
    InventoryStatistics,
)
from app.schemas.review import (
    ApprovedTestPlan,
    ReviewComment,
    ReviewDecision,
    ReviewMetadata,
    ReviewRequest,
    ReviewStatus,
    ScenarioReview,
    ScenarioReviewStatus,
)
from app.schemas.test_plan import (
    ApplicationSummary,
    CoverageSummary,
    Priority,
    Risk,
    ScenarioDependencies,
    ScenarioMetadata,
    TestAssumptions,
    TestCategory,
    TestModule,
    TestPlan,
    TestPriorities,
    TestScenario,
)
from app.schemas.trigger import (
    AIConfigInput,
    AuthenticationInput,
    CreateRunRequest,
    ExecutionConfigInput,
    ExecutionModeInput,
    MetadataInput,
    OutputConfigInput,
    RunResponse,
    RunStatusResponse,
    ScopeInput,
    TargetApplicationInput,
    TestRunRequest,
)

__all__ = [
    # Project schemas
    "CreateProjectRequest",
    "DashboardStats",
    "ProjectResponse",
    "ProjectStats",
    "RunListResponse",
    "TestRunResponse",
    # Trigger schemas
    "AIConfigInput",
    "AuthenticationInput",
    "CreateRunRequest",
    "ExecutionConfigInput",
    "ExecutionModeInput",
    "MetadataInput",
    "OutputConfigInput",
    "RunResponse",
    "RunStatusResponse",
    "ScopeInput",
    "TargetApplicationInput",
    "TestRunRequest",
    # Crawler schemas
    "ApiCallRecord",
    "AssetRecord",
    "AssetsCollection",
    "AuthRecord",
    "ButtonRecord",
    "CheckboxRecord",
    "CookieRecord",
    "CrawlEvent",
    "CrawlPackage",
    "CrawlRequest",
    "CrawlStatistics",
    "CrawlSummary",
    "DialogRecord",
    "DownloadRecord",
    "DropdownRecord",
    "FormRecord",
    "InputRecord",
    "NavigationEdge",
    "NavigationGraph",
    "PageRecord",
    "RadioRecord",
    "RedirectRecord",
    "ResponseTimeStats",
    "ScreenshotRecord",
    "SessionInfo",
    "TableRecord",
    "UploadRecord",
    "UserFlowRecord",
    # Inventory schemas
    "Inventory",
    "InventoryMetadata",
    "InventoryNavigation",
    "InventoryStatistics",
    # Test Plan schemas
    "ApplicationSummary",
    "CoverageSummary",
    "Priority",
    "Risk",
    "ScenarioDependencies",
    "ScenarioMetadata",
    "TestAssumptions",
    "TestCategory",
    "TestModule",
    "TestPlan",
    "TestPriorities",
    "TestScenario",
    # Review schemas
    "ApprovedTestPlan",
    "ReviewComment",
    "ReviewDecision",
    "ReviewMetadata",
    "ReviewRequest",
    "ReviewStatus",
    "ScenarioReview",
    "ScenarioReviewStatus",
]
